AllCops:
  Include:
    - '*.rb'

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 12

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false